apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eee-preview-app.fullname" . }}
  labels:
    {{- include "eee-preview-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eee-preview-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eee-preview-app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eee-preview-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -listen=:8080
            - -text=EEE preview {{ .Values.environmentName }} is ready
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "eee-preview-app.fullname" . }}-config
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
